### ISSUE TITLE
bilibili报错

### ISSUE THREAD

**Issue by HsiangNianian** [j4ger/firewatch#3]
Invalid Platform "bilibili"381703233
Available Platforms:

**Comment by j4ger** [comment]
或许你需要在中间加个空格🤔

**Comment by HsiangNianian** [comment]
啊我输入
/sub bilibili 381703233
就会显示
Invalid Platform "bilibili"
Available Platforms:

**Comment by j4ger** [comment]
啊这…
重启几次试试？
正常情况下插件加载的时候会显示目前支持的平台的，如果没有显示就说明没正确加载

**Comment by HsiangNianian** [comment]
qwq还是不行

**Comment by HsiangNianian** [comment]
config里面会有文件夹吗，如果有那可能就奇怪了，我这里没有

**Comment by j4ger** [comment]
应该不会
你用的什么平台的mirai…？有些特殊情况我可能没测试过…

**Comment by HsiangNianian** [comment]
> 应该不会
> 你用的什么平台的mirai…？有些特殊情况我可能没测试过…

mirai（core console）版本1.03
Dice!驱动器 by 安研色Shiki & 溯洄w4123 ver0.2.1(3)[2021-08-08 06:46:17] for CoolQ
MiraiNative: 当前系统: Linux
MiraiNative: 当前架构: amd64
MiraiNative v2.0.5-cp

**Comment by j4ger** [comment]
用README里的安装过程试试……？（虽然我觉得不太可能是版本问题，但确实没啥头绪）

**Comment by HsiangNianian** [comment]
> 用README里的安装过程试试……？（虽然我觉得不太可能是版本问题，但确实没啥头绪）

啊可以加一下好友吗
QQ：A2C29K9

**Comment by j4ger** [comment]
> > 用README里的安装过程试试……？（虽然我觉得不太可能是版本问题，但确实没啥头绪）
> 
> 啊可以加一下好友吗
> QQ：A2C29K9

最近挺忙的…有可能的话还是Issues里说吧
这个项目可能暂时不会维护了，可以先换别的看看…
