### ISSUE TITLE
难搞

### ISSUE THREAD

**Issue by HsiangNianian** [j4ger/firewatch#4]
![Screenshot_2022-03-12-15-40-45-44.jpg](https://user-images.githubusercontent.com/44714368/158008882-4613a856-d39f-4f92-80af-6c8f057d22eb.jpg)

已经按照readme来了

**Comment by j4ger** [comment]
啊这…
我也不知道怎么回事了…
目前没有太多精力维护这个项目，可以去找一下类似的插件，应该有不少的xddd
